[tool.poetry]
name = "protect_exporter"
version = "0.1.0"
description = "Export UniFi Protect metrics to Prometheus"
authors = ["Artanicus <artanicus@nocturnal.fi>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
absl-py = "^1.0.0"
requests = "^2.27.1"
prometheus-client = "^0.12.0"
asyncio = "^3.4.3"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
protect_exporter = 'protect_exporter:run'
